In [1]:
import torch
import numpy as np

import pyworld.toolkit.tools.torchutils as tu
import pyworld.toolkit.tools.visutils as vu
import pyworld.toolkit.tools.datautils as du
import pyworld.toolkit.tools.visutils.transform as T
import pyworld.toolkit.tools.visutils.jupyter as J

from pyworld.toolkit.nn.SANet import SANet2
from pyworld.algorithms.optimise.TripletOptimiser import PairTripletOptimiser

from anomapy import load

import datasets

env = "Breakout"
device = tu.device()

USING DEVICE: cuda


In [2]:
#LOAD DATA
def transform(episode):
    state = T.to_float(episode['state'][...])
    state = T.CHW(state)
    state = torch.from_numpy(state)
    #action = load.remove_redundant_actions(episode['action'], env) does this have an effect?
    action = episode['action'][:-1]
    action = action.astype(np.uint8)
    action = du.onehot(action, size=max(action) + 1) #...
    action = torch.from_numpy(action)
    return state[:-1], action, state[1:], torch.zeros(action.shape[1]).expand(action.shape)

episodes = [transform(e) for e in datasets.load("aad.clean", env, count=1)]

state_shape = tuple(episodes[0][0].shape[1:])
action_shape = (episodes[0][1].shape[1],)

loading dataset aad.clean...


IntProgress(value=0, max=1)

Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x04\x00\x00\x00d\x08\x00\x00\x00\x00\x84n\xce\xf…

In [3]:
print(state_shape, action_shape)

model = SANet2(state_shape, action_shape, 2)
opt = PairTripletOptimiser(model)

for episode in episodes:
    for s1,a1,s2,a2 in du.batch_iterator(*episode):
        opt((s1,a1),(s2,a2))
        print(opt.cma())






(3, 210, 160) (4,)
[419380.25]
[418058.78125]
[413097.22916667]
[398566.59375]
[339231.6828125]


In [4]:
tu.collect(model, (episode[0][0,1])

(100, 4)
torch.Size([100, 4])


In [26]:
a = np.random.randint(0,3,size=20)
print(a)
#z = np.random.randint(0,2,size=(a.shape[0], 3))
z = np.zeros((a.shape[0], 3))
z[np.arange(a.shape[0]),a] = 1






[0 2 0 0 1 2 1 1 2 2 0 1 1 2 1 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
